<?php

/**
 * Copyright © 2023 Lingaro sp. z o.o. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var \Lingaro\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Lingaro\StyleGuide\ViewModel\ColorsProvider $viewModel */
$viewModel = $block->getViewModel();
$colors = $viewModel->getColors();
?>
<?php if (!empty($colors)): ?>
    <ul class="style-guide-colors">
        <?php foreach ($colors as $color): ?>
            <li class="style-guide-color style-guide-color-<?= $escaper->escapeHtmlAttr($color->getCode()) ?>">
                <span class="style-guide-color-visualization"></span>
                <span class="style-guide-color-name" title="<?= $escaper->escapeHtmlAttr($color->getLabel()) ?>"><?= $escaper->escapeHtml($color->getLabel()) ?></span>
                <span class="style-guide-color-css-color"><?= $escaper->escapeHtml($color->getCssColor()) ?></span>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
