<?php

/**
 * Copyright © 2023 Lingaro sp. z o.o. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var \Lingaro\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<h1><?= $escaper->escapeHtml(__('H1 Heading')) ?></h1>
<h2><?= $escaper->escapeHtml(__('H2 Heading')) ?></h2>
<h3><?= $escaper->escapeHtml(__('H3 Heading')) ?></h3>
<h4><?= $escaper->escapeHtml(__('H4 Heading')) ?></h4>
<h5><?= $escaper->escapeHtml(__('H5 Heading')) ?></h5>
<h6><?= $escaper->escapeHtml(__('H6 Heading')) ?></h6>
