<?php

/**
 * Copyright © 2023 Lingaro sp. z o.o. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var \Lingaro\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Lingaro\StyleGuide\ViewModel\IconsProvider $viewModel */
$viewModel = $block->getViewModel();
$icons = $viewModel->getIcons();
?>
<?php if (!empty($icons)): ?>
<ul class="style-guide-icons">
    <?php foreach ($icons as $icon): ?>
        <li class="style-guide-icon">
            <span class="style-guide-icon-visualization">
                <span class="<?= $escaper->escapeHtmlAttr($icon->getCssClass()) ?>"></span>
            </span>
            <span class="style-guide-icon-name" title="<?= $escaper->escapeHtmlAttr($icon->getName()) ?>"><?= $escaper->escapeHtml($icon->getName()) ?></span>
        </li>
    <?php endforeach; ?>
</ul>
<?php endif ?>
