<?php

/**
 * Copyright © 2023 Lingaro sp. z o.o. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var \Lingaro\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */

$layouts = [
    'One Column' => '*/layout/onecolumn',
    'Two Columns Left' => '*/layout/twocolumnsleft',
    'Two Columns Right' => '*/layout/twocolumnsright',
    'Three Columns' => '*/layout/threecolumns',
]
?>
<ul>
    <?php foreach ($layouts as $title => $path): ?>
        <li>
            <a href="<?= $escaper->escapeHtmlAttr($block->getUrl($path)) ?>"><?= $escaper->escapeHtml(__($title)) ?></a>
        </li>
    <?php endforeach; ?>
</ul>
