<?php

/**
 * Copyright © 2023 Lingaro sp. z o.o. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var \Lingaro\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<p><a href="#"><?= $escaper->escapeHtml(__('Default link')) ?></a></p>
<p><a href="#" class="secondary"><?= $escaper->escapeHtml(__('Secondary link')) ?></a></p>
