<?php

/**
 * @copyright Copyright © 2021 Orba. All rights reserved.
 * @author    info@orba.co
 */

declare(strict_types=1);

/** @var \Orba\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<ol>
    <li>
        <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vestibulum justo a augue aliquam lobortis a eget dui. Vestibulum vel nulla pellentesque.</span>
    </li>
    <li>
        <span>Curabitur vestibulum mattis augue</span>
    </li>
    <li>
        <span>Mauris tempor scelerisque sapien, a pellentesque nibh porta in. Sed diam sapien, sollicitudin sit amet vehicula ut, sodales a magna. Etiam vestibulum vitae lacus ac varius.</span>
    </li>
</ol>