<?php

/**
 * @copyright Copyright © 2021 Orba. All rights reserved.
 * @author    info@orba.co
 */

declare(strict_types=1);

/** @var \Orba\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et tristique felis, sed efficitur felis. Maecenas fermentum eleifend libero sed ornare. Integer interdum felis non diam interdum, sed sagittis lacus ultrices. Mauris vel neque ut dui cursus pulvinar et ut purus. Aliquam tincidunt sed velit id porttitor.</p>
<p>Nunc ullamcorper nibh orci, et molestie risus gravida sit amet. Integer sit amet faucibus enim. Phasellus hendrerit tempus ultrices. Etiam vitae neque non ex elementum dignissim non bibendum elit. Integer varius odio id gravida finibus.</p>
