<?php

/**
 * @copyright Copyright © 2021 Orba. All rights reserved.
 * @author    info@orba.co
 */

declare(strict_types=1);

/** @var \Orba\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="style-guide-tooltips">
    <ul>
        <li>
            <a href="#"
               title="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
               data-mage-init='{"mage/tooltip": {}}'>
                <?= $escaper->escapeHtml(__('Tooltip with content from title attr')) ?>
            </a>
        </li>
        <li>
            <a href="#"
               data-mage-init='{"mage/tooltip": {"items": "*", "content": "Lorem ipsum dolor sit amet, <b>consectetur adipiscing</b> elit."}}'>
                <?= $escaper->escapeHtml(__('Tooltip with HTML content')) ?>
            </a>
        </li>
        <li>
            <a href="#"
               title="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
               data-mage-init='{"mage/tooltip": {"position": {"my": "left center", "at": "right+15 center", "collision": "flip flipfit"}}}'>
                <?= $escaper->escapeHtml(__('Tooltip positioned on right side')) ?>
            </a>
        </li>
    </ul>
</div>