<?php

/**
 * @copyright Copyright © 2021 Orba. All rights reserved.
 * @author    info@orba.co
 */

declare(strict_types=1);

/** @var \Orba\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<ul>
    <li>
        <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</span>
    </li>
    <li>
        <span>Nulla efficitur ut justo eget faucibus. Donec lectus risus, suscipit eu gravida vel, fringilla at leo. Morbi ornare nunc eu dolor pharetra cursus. Suspendisse orci nisl, ultrices non sagittis vitae.</span>
    </li>
    <li>
        <span>Praesent sagittis dapibus nibh.</span>
    </li>
</ul>