<?php

/*
 * @copyright Copyright © 2021 Orba. All rights reserved.
 * @author    info@orba.co
 */

declare(strict_types=1);

/** @var \Orba\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="block widget styleguide-sidebar-block">
    <div class="block-title">
        <strong role="heading" aria-level="2"><?= $escaper->escapeHtml(__('Sidebar element')) ?></strong>
    </div>
    <div class="block-content">
        <p>Lorem ipsum dolor sit amet</p>
    </div>
</div>