<?php

/**
 * Copyright © 2023 Lingaro sp. z o.o. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var \Lingaro\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="block widget styleguide-sidebar-block">
    <div class="block-title">
        <strong role="heading" aria-level="2"><?= $escaper->escapeHtml(__('Sidebar element')) ?></strong>
    </div>
    <div class="block-content">
        <p>Lorem ipsum dolor sit amet</p>
    </div>
</div>
